### ISSUE TITLE
Allow space (" ") characters in job names by default

### ISSUE THREAD

**Issue by JoshVanL** [diagridio/go-etcd-cron#46]
By default, we don't allow space (" ") characters from library consumer `Job` names. There isn't necessarily any reason why Jobs can't have space characters as Etcd treats [all key strings as a binary word](https://etcd.io/docs/v3.3/learning/api/#key-ranges), however there is likely going to be _some_ encoding errors either here in the lib, or by the consumer- based on the fact we are currently using [`"path/filepath".Join`](https://pkg.go.dev/path/filepath#Join), [implemented here](https://github.com/diagridio/go-etcd-cron/blob/2a1c6747974627691165eb96a2ca0202285d71eb/internal/key/key.go#L41), which _might_ cause some kind of escaping/parsing errors/discrepancies _somewhere_ (transforming the key with `"\ "` etc.). Ideally we'd move to using the more correct [`"path".Join`](https://pkg.go.dev/path#Join) for all key computations as implemented [here](https://github.com/diagridio/go-etcd-cron/pull/45).

I'm in favor of us changing allowing space characters, so long as we also change our key concatenations to use `path.Join`. I've added my thoughts [there](https://github.com/diagridio/go-etcd-cron/pull/45).

**Comment by cicoyle** [comment]
I am in favor of supporting space chars. This will support our use case with actors/reminders which allows spaces and Im sure there are cases where people want this as well.
